name: Mirror to Codeberg

on:
  push:
  delete:
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror GitHub to Codeberg
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository
        env:
          CODEBERG_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git clone --mirror "https://github.com/${{ github.repository }}.git" repository.git

          cd repository.git

          git remote set-url origin \
            "https://${CODEBERG_USERNAME}:${CODEBERG_TOKEN}@codeberg.org/${CODEBERG_USERNAME}/${GITHUB_REPOSITORY#*/}.git"

          git push --mirror