name: Mirror to Codeberg

on:
  push:
    branches:
      - '**'
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository to Codeberg
        env:
          CODEBERG_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git clone --mirror "https://github.com/${{ github.repository }}.git" repo.git
          cd repo.git

          git remote set-url --push origin \
            "https://${CODEBERG_USERNAME}:${CODEBERG_TOKEN}@codeberg.org/${CODEBERG_USERNAME}/${GITHUB_REPOSITORY#*/}.git"

          git push --mirror